const message = "Hello world!\n", message2="my name is",message_3=             "Antonis Skevis": string;
var listOfNums[10],b=1,tuc: number;
x[2] = 2 * x[4];

function start(): void {
limit = callfunc();
i = a and b;
j = a**b;
while (i != limit) {
if (i<2 or (not(k))) {
counter = counter + 1;
funccall(i);
return x+y;
};
j = j + 1;
};
}

-a;
a + b * (b / a);
4 + 50.0*x / 2.45;
(a) and(b ** cube(b));
(a <= b) and (d <= c);
(c+a) != (2*d);
a + b[(k)*2];
